sudo: false
language: node_js
node_js:
  - 6

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn install

env:
  - TEST_DIR=server

script:
  - cd $TEST_DIR && npm test
